# Generated by Django 4.1 on 2026-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0002_video_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
