# Generated by Django 4.1 on 2026-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Document', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Write your raw markdown here.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
